import { Router, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { AuthRequest } from '../middleware/auth';

const prisma = new PrismaClient();
export const contentRouter = Router();

contentRouter.get('/', async (req: AuthRequest, res: Response) => {
  const { page = '1', limit = '20', type } = req.query;
  const skip = (Number(page) - 1) * Number(limit);
  const where: any = { teamId: req.teamId };
  if (type) where.type = type;

  const [data, total] = await Promise.all([
    prisma.generatedContent.findMany({ where, skip, take: Number(limit), orderBy: { createdAt: 'desc' } }),
    prisma.generatedContent.count({ where }),
  ]);
  res.json({ success: true, data, pagination: { page: Number(page), limit: Number(limit), total, totalPages: Math.ceil(total / Number(limit)) } });
});

contentRouter.post('/generate', async (req: AuthRequest, res: Response) => {
  const schema = z.object({
    topic: z.string().min(2).max(500),
    type: z.enum(['blog', 'social', 'email', 'landing', 'ad']),
    tone: z.enum(['professional', 'casual', 'technical', 'inspirational', 'sales']).optional(),
    length: z.enum(['short', 'medium', 'long']).optional(),
    keywords: z.array(z.string()).optional(),
    targetAudience: z.string().optional(),
    includeSeo: z.boolean().optional(),
    relatedUrls: z.array(z.string()).optional(),
  });
  const data = schema.parse(req.body);

  // Stub — in production, call Azure OpenAI
  const wordCount = data.length === 'short' ? 200 : data.length === 'long' ? 1000 : 600;
  const title = `[AI Title] ${data.topic.substring(0, 80)}`;
  const body = `# ${title}\n\nThis is an AI-generated ${data.type} about ${data.topic}.\n\nGenerated in ${data.tone || 'professional'} tone.\n\nIntegrate Azure OpenAI for real generation.\n\n---\n*Generated by Honey AI*`;

  const content = await prisma.generatedContent.create({
    data: {
      teamId: req.teamId!,
      title, body,
      type: data.type,
      tone: data.tone || 'professional',
      topic: data.topic,
      keywords: JSON.stringify(data.keywords || []),
      model: 'azure/gpt-4',
      tokensUsed: Math.ceil(wordCount / 0.75),
    },
  });
  res.status(201).json({ success: true, data: content });
});

contentRouter.get('/:id', async (req: AuthRequest, res: Response) => {
  const content = await prisma.generatedContent.findUnique({ where: { id: req.params.id } });
  if (!content || content.teamId !== req.teamId) {
    res.status(404).json({ success: false, error: 'Content not found' });
    return;
  }
  res.json({ success: true, data: content });
});

contentRouter.delete('/:id', async (req: AuthRequest, res: Response) => {
  await prisma.generatedContent.delete({ where: { id: req.params.id, teamId: req.teamId } });
  res.json({ success: true, message: 'Content deleted' });
});